### ISSUE TITLE
Migrate from `googleai_dart` to official `google_generative_ai` API.

### ISSUE THREAD

**Issue by luisredondo** [davidmigloz/langchain_dart#332]
### Feature request

Google recently announced the official Dart/Flutter [SDK](https://pub.dev/packages/google_generative_ai) for their generative AI services. We should consider moving out of `googleai_dart` and use the official one instead.

### Motivation

Let Google handle the maintenance of their client and focus on bringing more value to the rest of LangChai.dart

### Your contribution

I can research and apply the migration, if possible.

### Requirements

- [ ] Investigate if `google_generative_ai` has feature parity with `googleai_dart`
- [ ] Migrate from `googleai_dart` to official `google_generative_ai`
- [ ] Make sure all tests are passing

**Comment by davidmigloz** [comment]
I haven't migrated yet to the official client, as it still less feature complete than `googleai_dart`.

The following features are not yet supported in the latest available version (0.2.1):
- Support for tuned models
- Support for `batchEmbedContents`

Side note: I don't understand why Google is still writing API clients manually in 2024, instead of investing that engineering time in developing a proper Dart API client generator.
