### ISSUE TITLE
Question about `OpenAIFunctionAgent` and the need for `extraPromptMessages`

### ISSUE THREAD

**Issue by orenagiv** [davidmigloz/langchain_dart#91]
Hey @davidmigloz ,
When using `OpenAIFunctionsAgent` and since it uses a Chat Model behind the scenes (and not plain LLM), is there a need / significance of using the extraPromptMessages like so:
```
final agent = OpenAIFunctionsAgent.fromLLMAndTools(
  llm: chatOpenAI,
  tools: [...],
  memory: memory,
  systemChatMessage: SystemChatMessagePromptTemplate.fromTemplate('...'),
  extraPromptMessages: [
    const MessagesPlaceholder(variableName: BaseMemory.defaultMemoryKey),
  ],
);
```

Or is it unnecessary? as the Chat Model relies on the history of messages that go through the OpenAI API messages list property of the `chatComplete()` method (and not as a plain text as part of the prompt).

**Comment by davidmigloz** [comment]
Hey @orenagiv ,

You don't need to add a placeholder for the memory if you use the `OpenAIFunctionsAgent.fromLLMAndTools` factory constructor, as the default prompt template already takes care of it. The Since it is a chat model, make sure you set `returnMessages` to true in your memory. So your example should look like this:

```dart
final memory = ConversationBufferMemory(returnMessages: true);
final agent = OpenAIFunctionsAgent.fromLLMAndTools(
  llm: chatOpenAI,
  tools: [...],
  memory: memory,
  systemChatMessage: SystemChatMessagePromptTemplate.fromTemplate('...'),
);
```

You can see how the default prompt template is constructed here:
https://github.com/davidmigloz/langchain_dart/blob/898d53502713ec2fd1ecc93e76e7f941123b81a5/packages/langchain_openai/lib/src/agents/functions.dart#L242-L260

I've improved the documentation in the PR: https://github.com/davidmigloz/langchain_dart/pull/94

Let me know if it's clear.
